version: '3'

services:
  postgres:
    image: postgres:13.10
    container_name: postgres
    ports:
      - 4568:5432
    env_file:
      - .env.local
    networks:
      - avito
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    container_name: golang_container
    env_file: .env.local
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - avito

networks:
  avito:
    driver: bridge

volumes:
  pg_data: